// <auto-generated />
namespace wawi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration02));
        
        string IMigrationMetadata.Id
        {
            get { return "202512122149391_migration02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
